#include "1_welcome\__init__.iss"
#include "2_license\__init__.iss"
#include "3_selectDir\__init__.iss"
#include "4_components\__init__.iss"
#include "5_ready\__init__.iss"
#include "6_install\__init__.iss"
#include "7_finished\__init__.iss"
