#include "user32.iss"
#include "check_cmd_param.iss"
#include "check_wot_running.iss"
#include "files_exist.iss"
#include "botva2\botva2.iss"
#include "findwot\findwot.iss"
#include "xml.iss"
#include "vcl\vcl.iss"
