#include "openwg\__init__.iss"
#include "user32.iss"
#include "check_cmd_param.iss"
#include "check_wot_running.iss"
#include "files_exist.iss"
#include "botva2\botva2.iss"
#include "bass\bass.iss"
#include "vcl\vcl.iss"
